name: Set Telegram Webhook

on:
  workflow_dispatch:

jobs:
  set-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Set Webhook to Cloudflare Worker
      run: |
        RESPONSE=$(curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/setWebhook?url=https://alpha-telegram-bot.abraxass0511.workers.dev/")
        echo "Response: $RESPONSE"
